chapter-14-make-web-applications-in-python-using/dj-1/book/urls.py
from django.conf.urls import url

from .views import IndexView, BookDetailView, CreateView
app_name = 'books'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$',  BookDetailView.as_view(), name='detail'),
    url(r'books/create/$', CreateView.as_view(), name='create'),
    
]

chapter-14-make-web-applications-in-python-using/dj-1/djver1/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('book.urls')),
]

chapter-14-make-web-applications-in-python-using/dj-1/book/models.py
from django.db import models
from django.core.urlresolvers import reverse
class Book(models.Model):
    name = models.CharField(max_length=150)
    author = models.CharField(max_length=150)
    price = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    image = models.CharField(max_length=100)

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return  reverse('books:detail', kwargs={'pk':self.pk})

chapter-14-make-web-applications-in-python-using/dj-1/book/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import  generic
from .models import Book

class IndexView(generic.ListView):
    template_name = 'book/index.html'

    def get_queryset(self):
        return Book.objects.all()

class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'book/detail.html'


class CreateView(generic.CreateView):
    model = Book
    fields = ['name', 'author', 'price', 'image']
    template_name = 'book/creat_book.html'

chapter-14-make-web-applications-in-python-using/dj-1/book/templates/book/base.html
{% load staticfiles %}
<html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'book/styles.css' %}">
    <title>Book store</title>
  </head>
  <body>
          <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'books:index' %}">Book Stores</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% with url_name=request.resolver_match.url_name %}
              <li class="{% if url_name == 'index' %} nav-item active {% endif %}">
                <a class="nav-link" href="{% url 'books:index' %}">Books <span class="sr-only">(current)</span></a>
              </li>
              <li class="{% if url_name == 'create' %} nav-item active {% endif %}">
                <a class="nav-link" href="{% url 'books:create' %}">Create a book</a>
              </li>
                {% endwith %}
            </ul>
          </div>
        </nav>
        {% block body %}
        {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

chapter-14-make-web-applications-in-python-using/dj-1/book/templates/book/creat_book.html
{% extends 'book/base.html' %}
{% load staticfiles %}
<html>

    <head>

    </head>
    <body>
{% block body %}

    <div class="container-fluid">
	    <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'book/forms_templates.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-sucess">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

    </body>
</html>

chapter-14-make-web-applications-in-python-using/dj-1/book/templates/book/delete.html
{% extends 'book/base.html' %}
{% load staticfiles %}
<html>

    <head>

    </head>
    <body>
{% block body %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock %}

    </body>
</html>

chapter-14-make-web-applications-in-python-using/dj-1/book/templates/book/detail.html
{% extends 'book/base.html' %}
{% load staticfiles %}
<html>

    <head>

    </head>
    <body>

        {% block body %}
            <h1>Name : {{ object.name }}</h1>
            <h1>Author: {{ object.author }}</h1>
            <h1>Price: $ {{ object.price }}</h1>
            <img src="{{ object.image }}">


        {% endblock %}

    </body>
</html>

chapter-14-make-web-applications-in-python-using/dj-1/book/templates/book/forms_templates.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small ">{{field.errors}}</span>

        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>

    </div>
{% endfor %}

chapter-14-make-web-applications-in-python-using/dj-1/book/templates/book/index.html
{% extends 'book/base.html' %}
{% load staticfiles %}
<html>

    <head>

    </head>
    <body>


        {% block body %}
        {% for book in object_list %}
            <img src="{{ book.image }}">
            <a href="{% url 'books:detail' book.id %}"><h1>{{ book.name }}</h1></a>
            <br>
        {% endfor %}
        {% endblock %}

    </body>
</html>